### ISSUE TITLE
change all 'df' arguments to 'tline' arguments?

### ISSUE THREAD

**Issue by light-matters** [vukics/Wigner_Time#1]
Idea being that the argument should be more descriptive to the concept and not the datatype? What exactly constitutes a timeline might change?

**Comment by light-matters** [comment]
Considering the implicit dependencies on certain columns being available (time, value etc.), I think this should happen. Probably we should just use `timeline` though for readability, though a clever person might want to use `time_`...

**Comment by vukics** [comment]
Agreed, `timeline` should be fine.
